version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.8.9-management
    hostname: rabbit1.pge.ce.gov.br
    volumes:
      - /appfiles/rabbitmq1/data/:/var/lib/rabbitmq
      - /appfiles/rabbitmq1/data/logs/:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
